#db:
#  image: mysql/mysql-server:5.5
#  environment:
#    MYSQL_ROOT_PASSWORD: rootpasswd
#    MYSQL_DATABASE: "RailsDocker_development"
#    MYSQL_USER: "sdbm"
#    MYSQL_PASSWORD: "sdbm"
#  ports:
#    - "3307:3307"
version: '2'
services:
  rails:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
      - solr
    volumes:
      - .:/RailsDocker
    env_file:
      - '.env.web'
  db:
  #  image: library/mysql:5.6.22
    image: mysql/mysql-server:5.5
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - '.env.db'
  solr:
    image: solr
    ports:
     - "8983:8983"
    links:
     - db
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - development
volumes:
  db-data:
    driver: local
  data:
    driver: local